### ISSUE TITLE
Please help :)

### ISSUE THREAD

**Issue by dhandyyusufs** [CyanLabs/RGBSync#16]
Can you help me a little bit :D I got an error when running the RGBSync.exe file. The error codes are just like this:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************ Exception Text ************
System.InvalidOperationException: Sequence contains no elements
   at RGBSync.Settings.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************ Loaded Assemblies ************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RGBSync
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGBSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RGB.NET.Core
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Core.DLL
----------------------------------------
RGB.NET.Devices.Asus
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Asus.DLL
----------------------------------------
RGB.NET.Groups
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Groups.DLL
----------------------------------------
RGB.NET.Devices.Razer
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Razer.DLL
----------------------------------------
RGB.NET.Devices.Msi
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Msi.DLL
----------------------------------------
RGB.NET.Devices.CorsairLink
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CorsairLink.DLL
----------------------------------------
RGB.NET.Devices.Novation
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Novation.DLL
----------------------------------------
RGB.NET.Devices.CoolerMaster
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CoolerMaster.DLL
----------------------------------------
RGB.NET.Devices.Logitech
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Logitech.DLL
----------------------------------------
RGB.NET.Devices.Corsair
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Corsair.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.2.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/System.ValueTuple.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
HidSharp
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/HidSharp.DLL
----------------------------------------

************ JIT Debugging ************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Can you help me, sir?﻿

**Comment by Fma965** [comment]
"System.InvalidOperationException: Sequence contains no elements" usually means you don't have a compatible motherboard, what motherboard do you have?

**Comment by dhandyyusufs** [comment]
My motherboard is ASUS ROG STRIX B250F, any idea what is the solution?

**Comment by Fma965** [comment]
no idea join the discord and someone might be able to help. https://discord.gg/V9PKGmU
