### ISSUE TITLE
App crashes on opening

### ISSUE THREAD

**Issue by BaaBaaBruh** [CyanLabs/RGBSync#8]
Just installed it, tried to run it, and it gave me the prompt to open ASUS AURA, but then stops working

**Comment by BaaBaaBruh** [comment]
any help?

**Comment by Fma965** [comment]
Not without a lot more information, motherboard model, keyboards, mice, devices trying to be used etc etc etc

**Comment by BaaBaaBruh** [comment]
Sorry, I have the:
ASUS x299-E (mobo)
ASUS GTX 1070 STRIX
2 sticks of G.SKILL TridentZ RGB (2x8GB)
Logitech G810 (Keyboard)

**Comment by Fma965** [comment]
Do you get a error message? may need to press "show details"

**Comment by BaaBaaBruh** [comment]
nope, it just crashes RIGHT when i try and open it

**Comment by BaaBaaBruh** [comment]
any fixes?

**Comment by BaaBaaBruh** [comment]
bump

**Comment by crashniels** [comment]
this also happens to me sometimes. it shows up in the tool bar for like 2 seconds and then disappears. What fixes it for me most of the time is to go into aura and turn it off and after that I start RGBSync.

**Comment by shanej77** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at RGBSync.Settings.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RGBSync
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGBSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RGB.NET.Core
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Core.DLL
----------------------------------------
RGB.NET.Devices.Asus
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Asus.DLL
----------------------------------------
RGB.NET.Groups
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Groups.DLL
----------------------------------------
RGB.NET.Devices.Razer
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Razer.DLL
----------------------------------------
RGB.NET.Devices.Msi
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Msi.DLL
----------------------------------------
RGB.NET.Devices.CorsairLink
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CorsairLink.DLL
----------------------------------------
RGB.NET.Devices.Novation
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Novation.DLL
----------------------------------------
RGB.NET.Devices.CoolerMaster
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CoolerMaster.DLL
----------------------------------------
RGB.NET.Devices.Logitech
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Logitech.DLL
----------------------------------------
RGB.NET.Devices.Corsair
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Corsair.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
HidSharp
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/HidSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
